# Generated by Django 5.2.8 on 2025-12-13 05:40

import secretary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0004_patientdocument_patientpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientpicture',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='document',
            field=models.FileField(upload_to=secretary.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='patientpicture',
            name='picture',
            field=models.ImageField(upload_to=secretary.models.picture_upload_path),
        ),
    ]
