# Generated by Django 6.0 on 2025-12-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0004_alter_appointment_id_alter_patient_id_and_more'),
        ('secretary', '0005_patientdocument_original_filename_and_more'),
    ]

    operations = [
    ]
