# Generated by Django 6.0 on 2025-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_billing_billingitem_transaction_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
