# Generated by Django 6.0 on 2025-12-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
